### ISSUE TITLE
Recent Oobabooga updates causing attribute errors

### ISSUE THREAD

**Issue by Dalhimar** [YenRaven/annoy_ltm#17]
I just updated to the most recent version of Ooba and annoy_ltm. As soon as I did, I started getting the following error:
```
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/anaconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/user/anaconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/user/anaconda3/lib/python3.10/site-packages/gradio/utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "/home/user/anaconda3/lib/python3.10/site-packages/gradio/utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/user/anaconda3/lib/python3.10/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/home/user/anaconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/home/user/anaconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/home/user/anaconda3/lib/python3.10/site-packages/gradio/utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "/home/user/AI/text-generation-webui/modules/chat.py", line 332, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, shared.history, state, regenerate, _continue, loading_message=True)):
  File "/home/user/AI/text-generation-webui/modules/chat.py", line 317, in generate_chat_reply
    for history in chatbot_wrapper(text, history, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "/home/user/AI/text-generation-webui/modules/chat.py", line 226, in chatbot_wrapper
    prompt = apply_extensions('custom_generate_chat_prompt', text, state, **kwargs)
  File "/home/user/AI/text-generation-webui/modules/extensions.py", line 193, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "/home/user/AI/text-generation-webui/modules/extensions.py", line 80, in _apply_custom_generate_chat_prompt
    return extension.custom_generate_chat_prompt(text, state, **kwargs)
  File "/home/user/AI/text-generation-webui/extensions/annoy_ltm/script.py", line 494, in custom_generate_chat_prompt
    return generator.custom_generate_chat_prompt(user_input, state, **kwargs)
  File "/home/user/AI/text-generation-webui/extensions/annoy_ltm/script.py", line 364, in custom_generate_chat_prompt
    embeddings = generate_embeddings(trimmed_msg, logger=logger)
  File "/home/user/AI/text-generation-webui/extensions/annoy_ltm/embeddings.py", line 28, in generate_embeddings
    input_embeds = shared.model.model.embed_tokens(input_ids)
  File "/home/user/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LlamaForCausalLM' object has no attribute 'embed_tokens'
```

I have been able to isolate the issue to this line of code:

```
    with torch.no_grad():
        input_embeds = shared.model.model.embed_tokens(input_ids)
```
Using `print(shared.model)` I got the following:

```
LlamaGPTQForCausalLM(
  (model): LlamaForCausalLM(
    (model): LlamaModel(
      (embed_tokens): Embedding(32000, 5120, padding_idx=0)
      (layers): ModuleList(
        (0-39): 40 x LlamaDecoderLayer(
          (self_attn): FusedLlamaAttentionForQuantizedModel(
            (qkv_proj): QuantLinear()
            (o_proj): QuantLinear()
            (rotary_emb): LlamaRotaryEmbedding()
          )
          (mlp): LlamaMLP(
            (act_fn): SiLUActivation()
            (down_proj): QuantLinear()
            (gate_proj): QuantLinear()
            (up_proj): QuantLinear()
          )
          (input_layernorm): LlamaRMSNorm()
          (post_attention_layernorm): LlamaRMSNorm()
        )
      )
      (norm): LlamaRMSNorm()
    )
    (lm_head): Linear(in_features=5120, out_features=32000, bias=False)
  )
)
```

It appears that the most recent updates added another layer of nesting, requiring the code to be changed to 

 ```
   with torch.no_grad():        
        input_embeds = shared.model.model.model.embed_tokens(input_ids)
```
After adjusting that, I now get the following error:

```
  File "/home/user/AI/text-generation-webui/extensions/annoy_ltm/script.py", line 395, in custom_generate_chat_prompt
    if shared.soft_prompt:
AttributeError: module 'modules.shared' has no attribute 'soft_prompt'
```
That is as far as I could get in with the time I had available today.

**Comment by YenRaven** [comment]
This should be fixed in main now. Thanks for the report!
