### ISSUE TITLE
failed to load character annoy metadata, generating from scratch... An error occurred while generating annoy database:

### ISSUE THREAD

**Issue by dinhosms** [YenRaven/annoy_ltm#22]
After loading any model and starting a new chat, I get this error after my first message. The chat freezes with the AI _is typing_ message and this error appears in cmd.
```
failed to load character annoy metadata, generating from scratch...
An error occurred while generating annoy database:
LlamaCppModel.encode() got an unexpected keyword argument 'return_tensors'
Traceback (most recent call last):
  File "D:\AI\text-generation-webui\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AI\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\AI\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "D:\AI\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "D:\AI\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "D:\AI\text-generation-webui\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\AI\text-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
  File "D:\AI\text-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 833, in run
    result = context.run(func, *args)
  File "D:\AI\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "D:\AI\text-generation-webui\modules\chat.py", line 329, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True)):
  File "D:\AI\text-generation-webui\modules\chat.py", line 297, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "D:\AI\text-generation-webui\modules\chat.py", line 231, in chatbot_wrapper
    prompt = apply_extensions('custom_generate_chat_prompt', text, state, **kwargs)
  File "D:\AI\text-generation-webui\modules\extensions.py", line 224, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "D:\AI\text-generation-webui\modules\extensions.py", line 100, in _apply_custom_generate_chat_prompt
    return extension.custom_generate_chat_prompt(text, state, **kwargs)
  File "D:\AI\text-generation-webui\extensions\annoy_ltm\script.py", line 486, in custom_generate_chat_prompt
    return generator.custom_generate_chat_prompt(user_input, state, **kwargs)
  File "D:\AI\text-generation-webui\extensions\annoy_ltm\script.py", line 352, in custom_generate_chat_prompt
    self.index_to_history_position, self.annoy_index, self.keyword_tally = self.annoy_manager.generate_annoy_db(params, state, kwargs['history'], self.keyword_tally, logger)
TypeError: cannot unpack non-iterable NoneType object
```
I don't know much about python and I don't know where to start to fix this. I disabled all extensions and flags and the error persisted

**Comment by flflow** [comment]
Same problem.
