### ISSUE TITLE
Error when starting a new chat with short greeting

### ISSUE THREAD

**Issue by soctib** [YenRaven/annoy_ltm#5]
Creating a new character with a short greeting like " What do you want to do?" causes the following error:
```
building annoy index took 0.03899884223937988 seconds...
Traceback (most recent call last):
  File "D:\oobabooga\installer_files\env\lib\site-packages\gradio\routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\oobabooga\installer_files\env\lib\site-packages\gradio\blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "D:\oobabooga\installer_files\env\lib\site-packages\gradio\blocks.py", line 930, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\oobabooga\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\oobabooga\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\oobabooga\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\oobabooga\installer_files\env\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "D:\oobabooga\text-generation-webui\modules\chat.py", line 319, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, shared.history, state, regenerate, _continue, loading_message=True)):
  File "D:\oobabooga\text-generation-webui\modules\chat.py", line 313, in generate_chat_reply
    for history in chatbot_wrapper(text, history, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "D:\oobabooga\text-generation-webui\modules\chat.py", line 226, in chatbot_wrapper
    prompt = apply_extensions('custom_generate_chat_prompt', text, state, **kwargs)
  File "D:\oobabooga\text-generation-webui\modules\extensions.py", line 193, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "D:\oobabooga\text-generation-webui\modules\extensions.py", line 80, in _apply_custom_generate_chat_prompt
    return extension.custom_generate_chat_prompt(text, state, **kwargs)
  File "D:\oobabooga\text-generation-webui\extensions\annoy_ltm\script.py", line 671, in custom_generate_chat_prompt
    return generator.custom_generate_chat_prompt(user_input, state, **kwargs)
  File "D:\oobabooga\text-generation-webui\extensions\annoy_ltm\script.py", line 615, in custom_generate_chat_prompt
    related_memories = retrieve_related_memories(
  File "D:\oobabooga\text-generation-webui\extensions\annoy_ltm\script.py", line 284, in retrieve_related_memories
    indices_distances[i] = (indices_distances[i][0], indices_distances[i][1] * weight)
IndexError: list index out of range
```

**Comment by YenRaven** [comment]
This is likely related to #2 and should be fixed in the current main branch.
