### ISSUE TITLE
No module named 'annoy'

### ISSUE THREAD

**Issue by rinaldop** [YenRaven/annoy_ltm#8]
I can´t load this extension.

INFO:Loading the extension "annoy_ltm"...
ERROR:Failed to load the extension "annoy_ltm".
Traceback (most recent call last):
  File "G:\oobabooga_windows\text-generation-webui\modules\extensions.py", line 34, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "G:\oobabooga_windows\text-generation-webui\extensions\annoy_ltm\script.py", line 9, in <module>
    from annoy import AnnoyIndex
ModuleNotFoundError: No module named 'annoy'

**Comment by Dalhimar** [comment]
The error you're getting makes it look like you don't have annoy installed in the same environment that the extension runs in. 
Did you have any errors when installing the requirements.txt?

**Comment by rinaldop** [comment]
My fault. I reinstall requirements.txt.
It is working now.
